# Generated by Django 5.2.6 on 2026-08-02 22:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0005_order_city_order_payment_method_order_phone_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
