from django.urls import path
from .views import (
    ProductListView,
    ProductDetailView,
    CheckoutView,
    MyOrdersView,
    AdminProductListView,
    AdminProductDetailView,
    BrandCategoryListView,
    PublicBrandListView,
    AdminOrderListView,
    AdminOrderDetailView,
    InitializePaymentView,
    VerifyPaymentView,
    KoraInitializePaymentView,
    KoraVerifyPaymentView,
    KoraWebhookView,
    PaystackInitializePaymentView,
    PaystackVerifyPaymentView,
)

urlpatterns = [
    path("", ProductListView.as_view(), name="product-list"),
    path("<int:pk>/", ProductDetailView.as_view(), name="product-detail"),
    path("checkout/", CheckoutView.as_view()),
    path("orders/", MyOrdersView.as_view()),
    path("brands/", PublicBrandListView.as_view(), name="public-brand-list"),
    path("admin/products/", AdminProductListView.as_view()),
    path("admin/products/<int:pk>/", AdminProductDetailView.as_view()),
    path("admin/meta/", BrandCategoryListView.as_view()),
    path("admin/orders/", AdminOrderListView.as_view()),
    path("admin/orders/<int:pk>/", AdminOrderDetailView.as_view()),
    path("payment/initialize/", InitializePaymentView.as_view(), name="payment-initialize"),
    path("payment/verify/<str:reference>/", VerifyPaymentView.as_view(), name="payment-verify"),
    path("payment/kora/initialize/", KoraInitializePaymentView.as_view(), name="kora-payment-initialize"),
    path("payment/kora/verify/<str:reference>/", KoraVerifyPaymentView.as_view(), name="kora-payment-verify"),
    path("payment/kora/webhook/", KoraWebhookView.as_view(), name="kora-webhook"),
    path("payment/webhook/", KoraWebhookView.as_view(), name="payment-webhook"),
    path("payment/paystack/initialize/", PaystackInitializePaymentView.as_view(), name="paystack-payment-initialize"),
    path("payment/paystack/verify/<str:reference>/", PaystackVerifyPaymentView.as_view(), name="paystack-payment-verify"),
]
